### ISSUE TITLE
[FAILED] Failed to start Network abstraction service

### ISSUE THREAD

**Issue by CRTX** [open-switch/opx-nas-daemon#21]
After a clean install of OPX 2.2.0.0-dev from the .bin file at openswitch.net

I login first, I run `apt update` and `apt-dist upgrade -y` to get the latest updates then I reboot.

Then when the switch reboots I get the `error [FAILED] Failed to start Network abstraction service.` at the startup logs.

After that I log in again and none of the switch interfaces show up except for `lo` and `eth0`

I was able to reproduce this twice in a row running those same two commands. The same thing happened after 2 fresh installs of OPX 2.2-dev.

Here's my opx-show-version output:

```
OS_NAME="OPX"
OS_VERSION="2.2.0"
PLATFORM="S3048-ON"
ARCHITECTURE="x86_64"
INTERNAL_BUILD_ID="OpenSwitch blueprint for Dell 1.0.0"
BUILD_VERSION="2.2.0.0-dev"
BUILD_DATE="2017-10-27T22:22:51+0000"
INSTALL_DATE="2017-11-30T02:49:55+0000"
SYSTEM_UPTIME= 1 hour, 56 minutes
Failed to get D-Bus connection: No such file or directory
SYSTEM_STATE= 
UPGRADED_PACKAGES=no
ALTERED_PACKAGES=no
```
For now I'll have to keep my switch without any updates so I can keep using it.

One last thing, I did not run into the same issue when I used OPX 2.1.0 previously

**Comment by jeff-yin** [comment]
The issue stems from the “apt-get dist-upgrade” step. The opx-bcm-lkm and opx-core packages got upgraded (unintentionally), and this is due to a discrepancy between what was packaged with the installer image vs. what is in the package repo (bintray). For those particular packages, the content of the package repo is out of date, yet they share the same version label, and in that case APT will by default install the version that is not installed.
 
The workaround for now is to prevent those packages from getting upgraded using the “apt-mark hold” command. Ex:
```
apt-mark hold opx-bcm-lkm
apt-mark hold opx-core
```
 
This issue will be resolved with the next release of OPX, in version 2.2.0.0-dev2. 

Will close the issue for now.
